# Generated by Django 5.2.6 on 2025-09-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarEmiten',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kode_emiten', models.CharField(blank=True, max_length=7, null=True)),
                ('nama_perusahaan', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_mulai', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
