# Generated by Django 5.2.6 on 2025-09-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftaremiten',
            name='tanggal_mulai',
        ),
    ]
