# Generated by Django 5.2.7 on 2025-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_app', '0002_remove_daftaremiten_tanggal_mulai'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPolaSaham',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kode_emiten', models.CharField(blank=True, max_length=7, null=True)),
                ('tanggal', models.DateField()),
                ('close', models.IntegerField()),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('value', models.IntegerField()),
                ('ch', models.IntegerField()),
                ('cl', models.IntegerField()),
                ('cc', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('ma5', models.IntegerField()),
                ('ma20', models.IntegerField()),
                ('ma50', models.IntegerField()),
                ('ma200', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SettingPersen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nama_settings', models.CharField()),
                ('setting_persen_naik', models.IntegerField()),
                ('setting_persen_turun', models.IntegerField()),
            ],
        ),
    ]
